### ISSUE TITLE
Which file has the finalized firmware?

### ISSUE THREAD

**Issue by awickert** [NorthernWidget-Skunkworks/Project-Haar#2]
And if there is one, could we whittle the repo down to just that in a folder labeled "Firmware"? (And/or decide to keep firmware in separate repos to handle the different HW/FW versioning.)

**Comment by bschulz1701** [comment]
Again, should have removed the "test" monicker, **`Haar_Firmware_Test.ino`** is the most final (still needs some cleanup but functionality is there) device firmware. `Haar_InterfaceDev.ino` is a development script used for testing the functionality of the Haar firmware be reading from the device (this code is meant to be run on the logger side for testing and development only)

**Comment by awickert** [comment]
I added some organization and READMEs with text cribbed from @bschulz1701 response.
